version: '3.8'

services:
  churn-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    restart: unless-stopped

  # Add for production:
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf